# Generated by Django 5.1.7 on 2025-03-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(max_length=200, null=True, upload_to='posts/images'),
        ),
    ]
